set nocompatible
syntax on

set laststatus=2 " Always show the status line at the bottom, even if you only have one window open.
set noerrorbells visualbell t_vb= " Disable audible bell
set backspace=indent,eol,start
set mouse+=a

set number relativenumber
set tabstop=4 shiftwidth=4 expandtab
set nowrap

set ignorecase smartcase " Case-insensitive search
set incsearch " Searching as you type

let g:vim_markdown_folding_disabled = 1
let g:vim_markdown_math = 1
