set nocompatible
syntax on

set laststatus=2 " Always show the status line at the bottom, even if you only have one window open.
set noerrorbells visualbell t_vb= " Disable audible bell
set backspace=indent,eol,start
set mouse+=a

set number relativenumber
set tabstop=2 shiftwidth=2 expandtab
set nowrap

set ignorecase smartcase " Case-insensitive search
set incsearch " Searching as you type

set textwidth=80
set formatoptions+=mM

let g:vim_markdown_folding_disabled = 1
let g:vim_markdown_math = 1

let g:tmux_navigator_no_wrap = 1

" keybindings
nnoremap q <nop>
noremap <C-c> <nop>
let mapleader = " "
nnoremap <leader>q <cmd>q<cr>

function s:sourceAnotherFile(path)
  if !empty(glob(a:path))
    exec "source " . a:path
  endif
endfunction

call s:sourceAnotherFile("~/.vim/vimrc_local")
