require("ycdzj.options")
require("ycdzj.colorscheme")
require("ycdzj.keymaps")
require("ycdzj.plugins.nvim-tree")
require("ycdzj.plugins.lualine")
require("ycdzj.plugins.telescope")
require("ycdzj.plugins.gitsigns")
