zstyle ':omz:update' mode reminder  # just remind me to update when it's time
ZSH_THEME="ys"
COMPLETION_WAITING_DOTS="true"
DISABLE_UNTRACKED_FILES_DIRTY="true"
plugins=(git fzf zsh-history-substring-search zsh-autosuggestions zsh-syntax-highlighting)
export ZSH=$HOME/.oh-my-zsh
source $ZSH/oh-my-zsh.sh

bindkey '^P' history-substring-search-up
bindkey '^N' history-substring-search-down

alias gs='git status'
alias gd='git diff'

if [ -f ~/.zshrc_local ]; then
  source ~/.zshrc_local
fi

